name: my first github action
on: [push]
jobs: 
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '14.17.0'
      - name : Intalling node_modules
        run : yarn
      - name : building project
        run : yarn build
      - name : Setup finish
        run : echo "hurray"  